# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/jammy64'
  config.vm.synced_folder 'data', '/data'
  config.vm.provider 'virtualbox' do |vb|
    vb.gui = false
    vb.memory = '1024'
  end
  config.vm.provision 'shell', path: 'install.sh'
end
