# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure('2') do |config|
  config.vm.box = 'digital_ocean'
  config.vm.box_url = 'https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box'
  config.vm.allowed_synced_folder_types = :rsync
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.private_key_path = '~/.ssh/vagrant'
  config.nfs.functional = false
  config.vm.synced_folder 'data', '/vagrant', type: 'rsync'
  config.vm.provision 'shell', path: 'ubuntu.sh'
  config.vm.provision 'shell', path: 'docker.sh'
  config.vm.provision 'shell', reboot: true
  config.vm.provision 'shell', path: 'assemblyline.sh'
  config.vm.hostname = 'assemblyline-docker'
  config.vm.provider "digital_ocean" do |d_o|
    d_o.token = ENV['DO_TOKEN']
    d_o.image = ENV['DO_IMAGE']
    d_o.ssh_key_name = ENV['DO_SSH']
    d_o.region = ENV['DO_REGION']
    d_o.size = ENV['DO_SIZE']
    d_o.backups_enabled = false
    d_o.ipv6 = false
    d_o.monitoring = false
  end
end
